services:
  editors-server:
    build:
      context: ..
      dockerfile: editors/Dockerfile
    container_name: editors-server
    restart: unless-stopped
    ports:
      - "3008:3008"
    volumes:
      - ../text/synonym_cache.db:/app/synonym_cache.db
      - ../text/word_cache:/app/word_cache

  #     volumes:
  # - /mnt/cache/appdata/creative-sketches/text:/app/text
